# Generated by Django 2.2.7 on 2019-11-09 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_personality', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TripCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories_text', models.CharField(max_length=100)),
            ],
        ),
    ]
